name: wi
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pytorch
  - torchvision
  - pytorch-cuda=12.4
  - scikit-learn
  - matplotlib
  - opencv
  - pillow
  - mss
  - pywin32
  - pynput
  - keyboard
  - cryptography
